function createfigure(xvector1, ymatrix1, DMatrix1)
%CREATEFIGURE(xvector1, ymatrix1, DMatrix1)
%  XVECTOR1:  bar xvector
%  YMATRIX1:  bar matrix data
%  DMATRIX1:  errorbar delta matrix data

%  Auto-generated by MATLAB on 05-Jun-2023 11:47:56

% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

% Create subplot
subplot1 = subplot(1,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix1,'Parent',subplot1);
set(bar1(5),'FaceColor',[0 0.168627450980392 0.52156862745098]);
set(bar1(4),'FaceColor',[0 0.219607843137255 1]);
set(bar1(3),'FaceColor',[0.23921568627451 0.490196078431373 1]);
set(bar1(2),'FaceColor',[0.470588235294118 0.650980392156863 1]);
set(bar1(1),'FaceColor',[0.749019607843137 0.83921568627451 1]);

% Create multiple error bars using matrix input to errorbar
errorbar(xvector1,ymatrix1,DMatrix1,'LineStyle','none','LineWidth',1,...
    'Color',[0 0 0]);

% Create ylabel
ylabel('Walk (%)','FontSize',18,'Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.36 5.64]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 64.8038202951256]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot1,[-1 1]);
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',18,'XLimitMethod','tight','XTick',...
    [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98],...
    'XTickLabel',{'GH20','GH10','GH5','GH3','GH1'},'YLimitMethod','tight',...
    'ZLimitMethod','tight');
